name: file_tailer
description: |
  Watch files whose tails may change.

  Useful for working with log files where contents gets appended.
  This library offers a similar functionality that the `tail` program
  available on most operating systems does.

version: "1.0.0"

repository: https://github.com/cathive/dart-file-tailer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  file: ^7.0.0
  path: ^1.9.0
  test: ^1.25.8

