name: file_tailer
description: Watch for file changes

version: "1.0.0"

repository: https://github.com/cathive/dart-file-tailer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.11.0

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
  file: ^7.0.0
  path: ^1.9.0
  test: ^1.25.8

